language: csharp
os:
  - linux
  - osx
sudo: false
mono:
  - beta
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ci/travis/travis_install.sh
compiler:
  - gcc
script: ./run_tests.py
after_success:
  - if [ x"${COVERAGE}" = x"true" ]; then coveralls; fi
env:
  global:
    - MONO_THREADS_PER_CPU=2000
    - MONO_MANAGED_WATCHER=disabled
    # Travis can run out of RAM, so we need to be careful here.
    - YCM_CORES=3
  matrix:
    # Don't forget to take the below matrix exclusions into account.
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.7
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.7 COVERAGE=true
    - USE_CLANG_COMPLETER=false YCMD_PYTHON_VERSION=2.6
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.6
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=3.3
matrix:
  exclude:
    - os: osx
      env: USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.7 COVERAGE=true
    - os: osx
      env: USE_CLANG_COMPLETER=false YCMD_PYTHON_VERSION=2.6
    - os: osx
      env: USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=3.3
    - os: linux
      env: USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.7
addons:
  # If this doesn't make much sense to you, see the travis docs:
  #    https://docs.travis-ci.com/user/migrating-from-legacy/
  apt:
    sources:
     # The Travis apt source whitelist can be found here:
     #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
     - ubuntu-toolchain-r-test  # for new libstdc++
     - llvm-toolchain-precise-3.7  # for clang
     - deadsnakes  # for various versions of python
     - kalakris-cmake # for a more recent version of cmake (needed for ninja-build)
    packages:
     - cmake
     - clang-3.7
     - ninja-build
     - python2.6
     - python2.6-dev
     - python2.7
     - python2.7-dev
     - python3.3
     - python3.3-dev
     - python-virtualenv
     - python-setuptools
cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
    - $HOME/.dnx/packages  # .Net packages?
    - $HOME/.multirust  # what multirust downloads
    - $HOME/.cargo  # cargo package deps
    - $TRAVIS_BUILD_DIR/clang_archives  # clang downloads
    # dependency compilation output
    - $TRAVIS_BUILD_DIR/third_party/racerd/target
    - $TRAVIS_BUILD_DIR/third_party/OmniSharpServer/OmniSharp/bin/Release
