language: generic
os:
  - linux
  - osx
dist: trusty
osx_image: xcode8
sudo: false
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ci/travis/travis_install.sh
compiler:
  - gcc
script:
  - ci/travis/travis_script.sh
after_success:
  - if [ "${COVERAGE}" == "true" ]; then bash <(curl -s https://codecov.io/bash); fi
env:
  global:
    # Travis can run out of RAM, so we need to be careful here.
    - YCM_CORES=3
    - COVERAGE=true
  matrix:
    - USE_CLANG_COMPLETER=false YCMD_PYTHON_VERSION=2.6
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.6
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.7
    - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=3.3
    - YCM_BENCHMARK=true YCMD_PYTHON_VERSION=3.3 COVERAGE=false
matrix:
  exclude:
    - os: osx
      env: USE_CLANG_COMPLETER=false YCMD_PYTHON_VERSION=2.6
    - os: osx
      env: USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.6
addons:
  # If this doesn't make much sense to you, see the travis docs:
  #    https://docs.travis-ci.com/user/migrating-from-legacy/
  apt:
    sources:
     # The Travis apt source whitelist can be found here:
     #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
     - ubuntu-toolchain-r-test  # for new libstdc++
     - george-edison55-precise-backports # for a more recent version of cmake (3.2.3)
     - mono # for installing Mono
    packages:
     - cmake-data
     - cmake
     # 4.9 is the first version of GCC with good enough C++11 support; in
     # particular regex support.
     - g++-4.9
     # Required to build the OmniSharp server.
     - mono-devel
     - ninja-build
     # Everything below is a Python build dep (though it depends on Python
     # version). We need them because pyenv builds Python.
     - libssl-dev
     - zlib1g-dev
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - wget
     - curl
     - llvm
     - libncurses5-dev
     - libncursesw5-dev
cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
    - $HOME/.npm  # Node packages from npm
    - $HOME/.cargo  # Cargo package deps
    - $HOME/.pyenv  # pyenv
    - $TRAVIS_BUILD_DIR/clang_archives  # Clang downloads
    - $TRAVIS_BUILD_DIR/third_party/racerd/target  # Racerd compilation
