version: '{build}'
environment:
  USE_CLANG_COMPLETER: true
  matrix:
  - msvc: 11
    arch: 32
  - msvc: 11
    arch: 64
  - msvc: 12
    arch: 32
  - msvc: 12
    arch: 64
  - msvc: 14
    arch: 32
  - msvc: 14
    arch: 64
install:
  - git submodule update --init --recursive
  - ps: $env:python = if ($env:arch -eq 32) { 'C:\Python27' } else { 'C:\Python27-x64' }
  - set PATH=%python%;%python%\Scripts;%PATH%
  - python --version
  # Manually setting PYTHONHOME for python 2.7.11 fix the following error when
  # running core tests: "ImportError: No module named site"
  # TODO: check if this is still needed when python 2.7.12 is released.
  - set PYTHONHOME=%python%
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:\get-pip.py')
  - python C:\get-pip.py
  - pip install -r test_requirements.txt
  - npm install -g typescript
  # The gnu rust compiler is used since, on windows 10, there is a workaround
  # needed for the msvc versions. However, the workaround sets Omnisharp build
  # config to 64-bit release mode which results in a failed build.
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.5.0-i686-pc-windows-gnu.exe'
  - rust-1.5.0-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  # TODO MinGW can be removed once the msvc rust compiler is used.
  - SET PATH=C:\Program Files (x86)\Rust\bin;C:\MinGW\bin;%PATH%
  - rustc -Vv
  - cargo -Vv
build_script:
  - python run_tests.py --msvc %MSVC%
# Disable automatic tests
test: off
cache:
  - 'C:\Users\appveyor\.cargo -> third_party\racerd'
  - 'third_party\racerd\target -> third_party\racerd'
